remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme 
title: [Cooklibri - Genera receptes saludables segons els ingredients fotografiats.]
description: [Software multiplataforma que ajuda a qualsevol persona a obtenir una recepta segons els ingredients que tingui disponibles, la recepta es saludable i es tindrà en compte les al·lèrgies i les intoleràncies que s'indiquen prèviament.]